version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: ""
    ignore:
      - dependency-name: org.eclipse.collections:eclipse-collections
        versions:
          - ">= 10.a"
      - dependency-name: org.eclipse.collections:eclipse-collections-api
        versions:
          - ">= 10.a"
      - dependency-name: net.javacrumbs.json-unit:json-unit-assertj
        versions:
          - ">= 3.0.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
