name: Autograding Action
description:  Action that autogrades assignments based on configurable quality criteria.

inputs:
  CONFIG:
    description: "Autograding configuration (if not set the default configuration will be used)"
    required: false
  CHECKS_NAME:
    description: "Name of the GitHub checks (if not set the default name will be used)"
    required: false
  PR_NUMBER:
    description: "Pull request number (if not set, PR comments will be skipped)"
    required: false
  TOKEN:
    description: "GitHub authentication token (GITHUB_TOKEN)"
    required: true
  HEAD_SHA:
    description: "SHA of the pull request head (if not set GITHUB_SHA will be used)"
    required: false
  FILES_PREFIX:
    description: "Prefix to remove from all paths so that files can be found in repository"
    required: false
  SKIP_ANNOTATIONS:
    description: "Skip the creation of annotations (for warnings and missed coverage) if not empty"
    required: false

runs:
  using: 'docker'
  image: 'docker://uhafner/autograding-github-action:2.2.0-SNAPSHOT'
  env:
    CONFIG: ${{ inputs.CONFIG }}
    CHECKS_NAME: ${{ inputs.CHECKS_NAME }}
    PR_NUMBER: ${{ inputs.PR_NUMBER }}
    TOKEN: ${{ inputs.TOKEN }}
    HEAD_SHA: ${{ inputs.HEAD_SHA }}
    FILES_PREFIX: ${{ inputs.FILES_PREFIX }}
    SKIP_ANNOTATIONS: ${{ inputs.SKIP_ANNOTATIONS }}

branding:
  icon: check-square
  color: green
