name: Autograding Action
description:  Action that autogrades assignments based on configurable quality critera.

inputs:
  CONFIG:
    description: "Autograding configuration"
    required: false
  TOKEN:
    description: "GitHub authentication token (GITHUB_TOKEN)"
    required: true
  HEAD_SHA:
    description: "SHA of the pull request head"
    required: false
  FILES_PREFIX:
    description: "Prefix to remove from all paths so that files can be found in repository"
    required: false

runs:
  using: 'docker'
  image: 'docker://uhafner/autograding-github-action'
  env:
    CONFIG: ${{ inputs.CONFIG }}
    CHECKS_NAME: ${{ inputs.CHECKS_NAME }}
    TOKEN: ${{ inputs.TOKEN }}
    HEAD_SHA: ${{ inputs.HEAD_SHA }}
    FILES_PREFIX: ${{ inputs.FILES_PREFIX }}

branding:
  icon: check
  color: red
