@startuml

package "Actions Plugin" {
[actions-plugin]
}

node "External-Dependencies" {
[analysis-model]

[autograding-model]

[org.eclipse.egit.github.core]
}

[actions-plugin] --> [analysis-model]
[actions-plugin] --> [autograding-model]
[actions-plugin] --> [org.eclipse.egit.github.core]

@enduml