name: CD

on:
  push:

jobs:
  build:
    name: Build and deploy to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get PR ID
        id: pr
        run: |
          PR_NUMBER=$(gh pr view --json "number" --jq ".number")
          echo "pr-number=${PR_NUMBER}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5
      - name: Echo GitHub PR
        run: echo "PR# ${{ steps.pr.outputs.pr-number }}"
      - name: Build and deploy
        env:
          DOCKER_IO_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
          DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
        run: mvn -ntp clean install
