name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Build and deploy
        env:
          DOCKER_IO_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
          DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
        run: mvn -ntp clean install -Pci
