name: Continuous Deployment

on:
  push:

jobs:
  build:
    name: Build and deploy to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.5
      - name: Build and deploy
        run: mvn -ntp clean install
      - name: Run Autograding
        uses: uhafner/autograding-github-action@v2.0.0-alpha-2
        env:
          DOCKER_IO_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
          DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
          CONFIG: >
            {
              "tests": {
                "tools": [
                  {
                    "id": "test",
                    "name": "Unittests",
                    "pattern": "**/test-classes/**/TEST*.xml"
                  }
                ],
                "name": "JUnit",
                "passedImpact": 10,
                "skippedImpact": -1,
                "failureImpact": -5,
                "maxScore": 100
              },
              "analysis": [
                {
                  "name": "Style",
                  "tools": [
                    {
                      "id": "checkstyle",
                      "name": "CheckStyle",
                      "pattern": "**/test-classes/**/checkstyle*.xml"
                    },
                    {
                      "id": "pmd",
                      "name": "PMD",
                      "pattern": "**/test-classes/**/pmd*.xml"
                    }
                  ],
                  "errorImpact": 1,
                  "highImpact": 2,
                  "normalImpact": 3,
                  "lowImpact": 4,
                  "maxScore": 100
                },
                {
                  "name": "Bugs",
                  "tools": [
                    {
                      "id": "spotbugs",
                      "name": "SpotBugs",
                      "pattern": "**/test-classes/**/spotbugs*.xml"
                    }
                  ],
                  "errorImpact": -11,
                  "highImpact": -12,
                  "normalImpact": -13,
                  "lowImpact": -14,
                  "maxScore": 100
                }
              ],
              "coverage": [
                {
                  "tools": [
                    {
                      "id": "jacoco",
                      "name": "Line Coverage",
                      "metric": "line",
                      "pattern": "**/test-classes/**/jacoco.xml"
                    },
                    {
                      "id": "jacoco",
                      "name": "Branch Coverage",
                      "metric": "branch",
                      "pattern": "**/test-classes/**/jacoco.xml"
                    }
                  ],
                  "name": "JaCoCo",
                  "maxScore": 100,
                  "coveredPercentageImpact": 1,
                  "missedPercentageImpact": -1
                },
                {
                  "tools": [
                    {
                      "id": "pit",
                      "name": "Mutation Coverage",
                      "metric": "mutation",
                      "pattern": "**/test-classes/**/mutations.xml"
                    }
                  ],
                  "name": "PIT",
                  "maxScore": 100,
                  "coveredPercentageImpact": 1,
                  "missedPercentageImpact": -1
                }
              ]
            }
