name: Enforce PR labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "bug,feature,enhancement,breaking,tests,documentation,internal,dependencies"
          message: "Maintainer needs to assign at least one label before merge"
